name: CI Workflow

on: [push, pull_request]

jobs:
  build-deploy-and-test:
    name: Build, Deploy, and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --force

      - name: Build Angular App
        run: npm run build -- --prod --base-href /ionic-e2e/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/your-app-name # The folder the action should deploy.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run E2E Tests
        run: npm run ionic-e2e:run:web
        env:
          BASE_URL: https://gitsachin.github.io/ionic-e2e/
