name: CI Workflow

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --force
      
      - name: Start Server
        run: npm start & npx wait-on --timeout 120000 http://localhost:4200/

      - name: Run E2E Tests
        run: SERVE_PORT=4200 npm run ionic-e2e:run:web

      - name: Generate Report
        run: npm run generate:report
        if: always()

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report
        if: always()

      - name: Build Project
        run: npm run build -- --prod --base-href="ionic-e2e"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages  # The branch to deploy to (GitHub Pages branch)
          folder: www  # The folder the action should deploy
          token: ${{ secrets.GITHUB_TOKEN }}

