name: CI Workflow

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --force

      # This step serves your application. Adjust the command according to how you would start your server.
      - name: Start Server
        run: npm start &

      - name: Wait for Server to Start
        run: npx wait-on --timeout 120000 http://localhost:4200/
        # You might need a way to ensure the server has started before running tests. Consider using a tool like wait-on.

      # Now run your E2E tests against the locally served application. Ensure your test configuration targets the correct local URL.
      - name: Run E2E Tests
        run: npm run ionic-e2e:run:web
        # Ensure your tests are configured to hit the local server's URL. By default, this might be something like http://localhost:4200